apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  ports:
  - port: 8000
    name: http
    targetPort: http
    protocol: TCP
  selector:
    app: flask
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: flask
  name: flask
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
      labels:
        app: flask
      name: flask
    spec:
      containers:
        - name: flask
          image: mrsabath/ms-flask:v0.1
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8000
            protocol: TCP
